<a href="https://colab.research.google.com/github/salianbharat/BE_DS_Assignment/blob/main/IPL_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This is Analysis of IPL Dataset between 2008-2020.


> Data set use are - 1.IPL Ball-by-Ball 2008-2020.csv
                    2. IPL Matches 2008-2020.csv






Importing the required Libraries.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Uploading the Dataset in Colab

In [ ]:
from google.colab import files
upload_file = files.upload ()

Saving IPL Ball-by-Ball 2008-2020.csv to IPL Ball-by-Ball 2008-2020.csv


In [ ]:
#Uploading Another Data set
from google.colab import files
upload_file = files.upload ()

Saving IPL Matches 2008-2020.csv to IPL Matches 2008-2020.csv


In [ ]:
#Basic EDA
byb = pd.read_csv("IPL Ball-by-Ball 2008-2020.csv")
byb.head()

id  inning  over  ball      batsman  non_striker     bowler  \
0  335982       1     6     5   RT Ponting  BB McCullum  AA Noffke   
1  335982       1     6     6  BB McCullum   RT Ponting  AA Noffke   
2  335982       1     7     1  BB McCullum   RT Ponting     Z Khan   
3  335982       1     7     2  BB McCullum   RT Ponting     Z Khan   
4  335982       1     7     3   RT Ponting  BB McCullum     Z Khan   

   batsman_runs  extra_runs  total_runs  non_boundary  is_wicket  \
0             1           0           1             0          0   
1             1           0           1             0          0   
2             0           0           0             0          0   
3             1           0           1             0          0   
4             1           0           1             0          0   

  dismissal_kind player_dismissed fielder extras_type           batting_team  \
0            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
1            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
2            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
3            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
4            NaN              NaN     NaN         NaN  Kolkata Knight Riders   

                  bowling_team  
0  Royal Challengers Bangalore  
1  Royal Challengers Bangalore  
2  Royal Challengers Bangalore  
3  Royal Challengers Bangalore  
4  Royal Challengers Bangalore

In [ ]:
matches = pd.read_csv("IPL Matches 2008-2020.csv")
matches.head()

id        city        date player_of_match  \
0  335982   Bangalore  2008-04-18     BB McCullum   
1  335983  Chandigarh  2008-04-19      MEK Hussey   
2  335984       Delhi  2008-04-19     MF Maharoof   
3  335985      Mumbai  2008-04-20      MV Boucher   
4  335986     Kolkata  2008-04-20       DJ Hussey   

                                        venue  neutral_venue  \
0                       M Chinnaswamy Stadium              0   
1  Punjab Cricket Association Stadium, Mohali              0   
2                            Feroz Shah Kotla              0   
3                            Wankhede Stadium              0   
4                                Eden Gardens              0   

                         team1                        team2  \
0  Royal Challengers Bangalore        Kolkata Knight Riders   
1              Kings XI Punjab          Chennai Super Kings   
2             Delhi Daredevils             Rajasthan Royals   
3               Mumbai Indians  Royal Challengers Bangalore   
4        Kolkata Knight Riders              Deccan Chargers   

                   toss_winner toss_decision                       winner  \
0  Royal Challengers Bangalore         field        Kolkata Knight Riders   
1          Chennai Super Kings           bat          Chennai Super Kings   
2             Rajasthan Royals           bat             Delhi Daredevils   
3               Mumbai Indians           bat  Royal Challengers Bangalore   
4              Deccan Chargers           bat        Kolkata Knight Riders   

    result  result_margin eliminator method    umpire1         umpire2  
0     runs          140.0          N    NaN  Asad Rauf     RE Koertzen  
1     runs           33.0          N    NaN  MR Benson      SL Shastri  
2  wickets            9.0          N    NaN  Aleem Dar  GA Pratapkumar  
3  wickets            5.0          N    NaN   SJ Davis       DJ Harper  
4  wickets            5.0          N    NaN  BF Bowden     K Hariharan

In [ ]:
byb.shape

(193468, 18)

In [ ]:
matches.shape

(816, 17)

**Ball By Ball have 18 columns with 193468 Rows & IPL matches have 17 columns with 816 rows**

This means there were total 816 matches played.

**we will try to Analysis these data from following question perspective -**
1. What was the count of matches played in each season?
2. How many runs were scored in each season?
3. What were the runs scored per match in different seasons?
4. Who has umpired the most?
5. Which team has won the most tosses?
6. What does the team decide after winning the toss?
7. How does the toss decision vary across seasons?
8. Does winning the toss imply winning the game?
9. How many times has the chasing team won the match?
10. Which all teams had won this tournament?
11. Which team has played the most number of matches?
12. Which team has won the most number of times?
13. Which team has the highest winning percentage?
14. Is there any lucky venue for a particular team?
15. Innings wise comparison between teams
16. Which team has scored the most number of 200+ scores?
17. Which team has conceded 200+ scores the most?
18. What was the highest run scored by a team in a single match?
19. Which is the biggest win in terms of run margin?
20. Which batsmen have played the most number of balls?
21. Who are the leading run-scorers of all time?
22. Who has hit the most number of 4's?
23. Who has hit the most number of 6's?
24. Who has the highest strike rate?
25. Who is the leading wicket-taker?
26. Which stadium has hosted the most number of matches?
27. Who has won the most MOM awards?
28. What is the count of fours hit in each season?
29. What is the count of sixes hit in each season?
30. What is the count of runs scored from boundaries in each season?
31. What is the run contribution from boundaries in each season?
32. Which team has scored the most runs in the first 6 overs?
33. Which team has scored the most runs in the last 4 overs?
34. Which team has the best scoring run-rate in the first 6 overs?
35. Which team has the best scoring run-rate in the last 4 overs?

In [ ]:
byb.columns

Index(['id', 'inning', 'over', 'ball', 'batsman', 'non_striker', 'bowler',
       'batsman_runs', 'extra_runs', 'total_runs', 'non_boundary', 'is_wicket',
       'dismissal_kind', 'player_dismissed', 'fielder', 'extras_type',
       'batting_team', 'bowling_team'],
      dtype='object')

In [ ]:
byb.describe()

id         inning           over           ball  \
count  1.934680e+05  193468.000000  193468.000000  193468.000000   
mean   7.567688e+05       1.482131       9.177027       3.615967   
std    3.060971e+05       0.499682       5.676848       1.807128   
min    3.359820e+05       1.000000       0.000000       1.000000   
25%    5.012270e+05       1.000000       4.000000       2.000000   
50%    7.292970e+05       1.000000       9.000000       4.000000   
75%    1.082628e+06       2.000000      14.000000       5.000000   
max    1.237181e+06       2.000000      19.000000       9.000000   

        batsman_runs     extra_runs     total_runs   non_boundary  \
count  193468.000000  193468.000000  193468.000000  193468.000000   
mean        1.240231       0.066414       1.306645       0.000083   
std         1.610867       0.339991       1.598802       0.009094   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         1.000000       0.000000       1.000000       0.000000   
75%         1.000000       0.000000       1.000000       0.000000   
max         6.000000       7.000000       7.000000       1.000000   

           is_wicket  
count  193468.000000  
mean        0.049078  
std         0.216031  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000

In [ ]:
matches.columns

Index(['id', 'city', 'date', 'player_of_match', 'venue', 'neutral_venue',
       'team1', 'team2', 'toss_winner', 'toss_decision', 'winner', 'result',
       'result_margin', 'eliminator', 'method', 'umpire1', 'umpire2'],
      dtype='object')

In [ ]:
matches.describe()

id  neutral_venue  result_margin
count  8.160000e+02     816.000000     799.000000
mean   7.563496e+05       0.094363      17.321652
std    3.058943e+05       0.292512      22.068427
min    3.359820e+05       0.000000       1.000000
25%    5.012278e+05       0.000000       6.000000
50%    7.292980e+05       0.000000       8.000000
75%    1.082626e+06       0.000000      19.500000
max    1.237181e+06       1.000000     146.000000

In [ ]:
#1. What was the count of matches played in each season?

matches['season'] = pd.DatetimeIndex(matches['date']).year
matches.head()

In [ ]:
matchesperseasion=matches.groupby(['season'])['id'].count()
matchesperseasion.head()

season
2008    58
2009    57
2010    60
2011    73
2012    74
Name: id, dtype: int64

In [ ]:
#How many runs were scored in each season?
byb.head(10)

id  inning  over  ball      batsman  non_striker     bowler  \
0  335982       1     6     5   RT Ponting  BB McCullum  AA Noffke   
1  335982       1     6     6  BB McCullum   RT Ponting  AA Noffke   
2  335982       1     7     1  BB McCullum   RT Ponting     Z Khan   
3  335982       1     7     2  BB McCullum   RT Ponting     Z Khan   
4  335982       1     7     3   RT Ponting  BB McCullum     Z Khan   
5  335982       1     7     4  BB McCullum   RT Ponting     Z Khan   
6  335982       1     7     5   RT Ponting  BB McCullum     Z Khan   
7  335982       1     7     6  BB McCullum   RT Ponting     Z Khan   
8  335982       1     8     1  BB McCullum   RT Ponting  JH Kallis   
9  335982       1     8     2  BB McCullum   RT Ponting  JH Kallis   

   batsman_runs  extra_runs  total_runs  non_boundary  is_wicket  \
0             1           0           1             0          0   
1             1           0           1             0          0   
2             0           0           0             0          0   
3             1           0           1             0          0   
4             1           0           1             0          0   
5             1           0           1             0          0   
6             1           0           1             0          0   
7             1           0           1             0          0   
8             0           0           0             0          0   
9             0           0           0             0          0   

  dismissal_kind player_dismissed fielder extras_type           batting_team  \
0            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
1            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
2            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
3            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
4            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
5            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
6            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
7            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
8            NaN              NaN     NaN         NaN  Kolkata Knight Riders   
9            NaN              NaN     NaN         NaN  Kolkata Knight Riders   

                  bowling_team  
0  Royal Challengers Bangalore  
1  Royal Challengers Bangalore  
2  Royal Challengers Bangalore  
3  Royal Challengers Bangalore  
4  Royal Challengers Bangalore  
5  Royal Challengers Bangalore  
6  Royal Challengers Bangalore  
7  Royal Challengers Bangalore  
8  Royal Challengers Bangalore  
9  Royal Challengers Bangalore

from matplotlib import pyplot as plt
_df_0['over'].plot(kind='hist', bins=20, title='over')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['ball'].plot(kind='hist', bins=20, title='ball')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['batsman_runs'].plot(kind='hist', bins=20, title='batsman_runs')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3['total_runs'].plot(kind='hist', bins=20, title='total_runs')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('batsman').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('non_striker').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_6.groupby('bowler').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='over', y='ball', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_8.plot(kind='scatter', x='ball', y='batsman_runs', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_9.plot(kind='scatter', x='batsman_runs', y='total_runs', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['id']
  ys = series['ball']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('id', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('batsman')):
  _plot_series(series, series_name, i)
  fig.legend(title='batsman', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('id')
_ = plt.ylabel('ball')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['id']
  ys = series['ball']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_11.sort_values('id', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('non_striker')):
  _plot_series(series, series_name, i)
  fig.legend(title='non_striker', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('id')
_ = plt.ylabel('ball')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['id']
  ys = series['ball']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_12.sort_values('id', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('bowler')):
  _plot_series(series, series_name, i)
  fig.legend(title='bowler', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('id')
_ = plt.ylabel('ball')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  from matplotlib import pyplot as plt
  import seaborn as sns
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['id']
  ys = series['batsman_runs']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_13.sort_values('id', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('batsman')):
  _plot_series(series, series_name, i)
  fig.legend(title='batsman', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('id')
_ = plt.ylabel('batsman_runs')

from matplotlib import pyplot as plt
_df_14['over'].plot(kind='line', figsize=(8, 4), title='over')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_15['ball'].plot(kind='line', figsize=(8, 4), title='ball')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_16['batsman_runs'].plot(kind='line', figsize=(8, 4), title='batsman_runs')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_17['total_runs'].plot(kind='line', figsize=(8, 4), title='total_runs')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['non_striker'].value_counts()
    for x_label, grp in _df_18.groupby('batsman')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('batsman')
_ = plt.ylabel('non_striker')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['bowler'].value_counts()
    for x_label, grp in _df_19.groupby('non_striker')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('non_striker')
_ = plt.ylabel('bowler')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['batsman'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='over', y='batsman', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_21['non_striker'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_21, x='over', y='non_striker', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_22['bowler'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_22, x='over', y='bowler', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_23['batsman'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_23, x='ball', y='batsman', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
total_score=byb.groupby(['season'])['total_runs'].sum().reset_index()
total_score

KeyError: 'season'

In [ ]:
#who has the umpire the most
ump1=matches(['umpire'])


TypeError: 'DataFrame' object is not callable